### ISSUE TITLE
It does not work on an separe install from the main package

### ISSUE THREAD

**Issue by evandrocoan** [shagabutdinov/sublime-goto-last-edit-enhanced#1]
### It does not work on an separe install from the main package

It is using the context:
```
    "context": [
      {"key": "setting.sublime_enhanced_keybindings", "operator": "equal", "operand": true},
    ]
```

There is no context as that when this package is installed standalone. Firstly I tough it was the `alt+z` problem, then I search for another keybinding, when I realize that context embedded.
```
[
    {
        "keys": ["ctrl+shift+keypad_minus"],
        "command": "goto_last_edit_enhanced",
    },

    {
        "keys": ["ctrl+shift+keypad_plus"],
        "command": "goto_last_edit_enhanced",
        "args":
        {
            "backward": true
        },
    },
]
```

**Comment by shagabutdinov** [comment]
Please, follow this instruction in order to activate default keybindings: https://github.com/shagabutdinov/sublime-enhanced#default-keybinding-activation
