### ISSUE TITLE
Unbound history size

### ISSUE THREAD

**Issue by Wramberg** [shagabutdinov/sublime-goto-last-edit-enhanced#3]
Hi @shagabutdinov 
I have discovered a conflict between my terminal plugin (https://github.com/Wramberg/TerminalView) and this one. My plugin works by calling self.view.replace(...) many times to update a terminal shown in a standard ST3 view.

Unfortunately with this plugin active it causes an unbounded memory usage since (I guess) each time something is replaced in the terminal your plugin makes a region.

Have you considered limiting the history size for this plugin to avoid such issues ? I would be happy to make a PR showing what i mean.

**Comment by shagabutdinov** [comment]
Hi, @Wramberg! It would be great if you'll prepare a PR in order to prevent this memory leak. I think clean up should be made somewhere in `on_modified` handler. 

Thank you!
