### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by f-w** [shagabutdinov/sublime-goto-last-edit-enhanced#5]
tried on st3 3126 win 10, key binding doesn't work. calling from command palette doesn't work either.

**Comment by shagabutdinov** [comment]
Can you show me the console log, please?

**Comment by shagabutdinov** [comment]
Did you activate sublime key bindings (https://github.com/shagabutdinov/sublime-enhanced#default-keybinding-activation)?

**Comment by f-w** [comment]
Works after activating.
I was expecting it works across files like webstorm. After reviewing readme I realized it only works within a file. I guess that's why calling from command palette doesn't work earlier.
thx for quick response.

**Comment by shagabutdinov** [comment]
No problem, glad I could help. That is an interesting idea to have an across files implementation. What use cases of such approach do you have?

**Comment by f-w** [comment]
I found myself doing cross file editing quite often and relying on this feature heavily in webstorm. None of st plugins as I know of supports it so it should be a good contribution. Unfortunately I am not a python expert.

Sent via phone

On Jul 19, 2017, at 7:57 PM, Leonid Shagabutdinov <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem, glad I could help. That is an interesting idea to have an across files implementation. What use cases of such approach do you have?

-

**Comment by shagabutdinov** [comment]
As I find out you do not have to be a python expert in order to make sublime plugins ;)
